export const text = `Lorem ipsum dol <mark>nunc</mark> or sit amet, consectetur adipiscing elit. Nulla nec facilisis odio, et accumsan sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque id elit vel tortor semper ornare et nec ligula. Curabitur sed molestie justo, quis ultricies turpis. Nunc odio leo, tristique id diam a, tincidunt euismod ligula. Vestibulum sed erat sit amet sem aliquet ullamcorper. Nullam ante libero, convallis ac leo et, vestibulum dignissim orci. Pellentesque quis orci arcu. Ut et congue massa. Proin sed blandit orci, nec aliquam justo. Vestibulum tempor, tortor nec varius blandit, sem lacus interdum diam, sed volutpat velit risus id orci. Sed dapibus nibh a magna aliquam malesuada. Etiam facilisis vel risus viverra tristique. Ut molestie mollis finibus.

Curabitur a lectus <mark>nunc</mark> id elit cursus tempor. Nulla a erat sit amet ipsum vulputate molestie a non ex. Curabitur eget faucibus lorem, sit amet pretium nibh. Sed vitae orci varius, finibus libero nec, luctus nisi. Nullam suscipit neque vitae imperdiet fermentum. Nulla nisi risus, vulputate pulvinar sollicitudin et, interdum non ipsum. Cras tristique eros mauris. Nunc pulvinar turpis est, vitae maximus libero consectetur non. Morbi mattis lorem tellus, ac maximus sapien faucibus rutrum. Vestibulum at libero a orci iaculis commodo nec id sapien. Nulla in libero vitae libero porttitor finibus. Fusce congue tellus nunc, sit amet vestibulum arcu pulvinar eu. Quisque fermentum orci at neque lobortis, id accumsan lacus sollicitudin.

Suspendisse a rhoncus dui. Integer varius est vitae metus suscipit laoreet. Suspendisse sit amet mollis enim. Mauris gravida elit in dolor porttitor consectetur. Nullam at fermentum justo, vitae sagittis ex. Sed lobortis justo vitae nunc dignissim, quis commodo nunc iaculis. Quisque nec ex erat. Fusce vel sagittis libero. Fusce sed massa at massa euismod auctor ut vel mi.

Cras hendrerit et <mark>nunc</mark> in condimentum. Maecenas faucibus ac urna sit amet pretium. Donec in turpis sed risus suscipit venenatis at id eros. Nunc eu interdum ex, quis tristique ex. Curabitur blandit sapien non dapibus fringilla. Aenean id lobortis dui. Vivamus ultrices lobortis fringilla. Fusce molestie lectus aliquam, placerat arcu in, feugiat magna. Maecenas at lectus in felis venenatis interdum. Maecenas sodales nulla pharetra, iaculis lorem sed, malesuada neque.

Aenean ligula dolor, sagittis sit amet erat et, tincidunt lacinia quam. Aenean aliquam arcu et imperdiet sagittis. Ut tincidunt leo vel finibus lobortis. Quisque quis nisl at est hendrerit tristique. Curabitur tempor neque velit, et porta arcu semper eget. Suspendisse iaculis lacinia tortor mollis porta. Etiam nunc nunc, tincidunt non mi nec, dictum interdum elit. Aenean ultricies rhoncus lectus gravida convallis. Quisque suscipit eros in libero aliquam, porta semper ante euismod. Integer dignissim erat et massa commodo rutrum. Ut et ex suscipit est auctor viverra sed at dolor. Vestibulum sagittis rhoncus fermentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras interdum neque eget lectus pharetra bibendum. In malesuada dui et urna placerat auctor.

`;
